// ENUM FOR ACTION NAMES
export enum ActionType {
  SEARCH_REPOSITORIES = 'search_repositories',
  SEARCH_REPOSITORIES_SUCCESS = 'search_repositories_success',
  SEARCH_REPOSITORIES_ERROR = 'search_repositories_error',
  LOAD_CATEGORIES = 'load_categories',
  LOAD_CATEGORIES_SUCCESS = 'load_categories_success',
  LOAD_CATEGORIES_ERROR = 'load_categories_error',
  LOAD_PRODUCTS = 'load_products',
  LOAD_PRODUCTS_SUCCESS = 'load_products_success',
  LOAD_PRODUCTS_ERROR = 'load_products_error',
  LOAD_CART_SUCCESS = 'load_cart_success',
  LOAD_CART_ERROR = 'load_cart_error',
  ADD_TO_CART = 'add_to_cart',
  REMOVE_FROM_CART = 'remove_from_cart',
  ADD_QUANTITY_TO_CART = 'add_quantity_to_cart',
  SUBTRACT_QUANTITY_FROM_CART = 'subtract_quantity_from_cart',
  DELETE_FROM_CART = 'delete_from_cart',
  PUSH_ITEMS_TO_CHECKOUT = 'push_items_to_checkout',
  EMPTY_CART = 'empty_cart',
  FETCH_USER = 'fetch_user',
  SIGNUP_USER_SUCCESS = 'signup_user_success',
  SIGNUP_USER_ERROR = 'signup_user_error',
  SIGNOUT_USER_SUCCESS = 'signout_user_success',
  SIGNOUT_USER_ERROR = 'signout_user_error',
  LOGIN_USER_SUCCESS = 'login_user_success',
  LOGIN_USER_ERROR = 'login_user_error',
  LOGOUT_USER = 'logout_user',
}
